version: "3.8"
services:
  flask-app:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
